MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/incremental_learning_ResNet50_C4/RPN_first_10_classes_40k_steps/model_trim_optimizer_iteration.pth"
  BACKBONE:
    CONV_BODY: "R-50-C4"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
  RPN:
    USE_FPN: False
    ANCHOR_STRIDE: (16,)
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: False
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.0625,)
    POOLER_SAMPLING_RATIO: 0
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    NUM_CLASSES: 21 # total classes : 20 + 1
    NAME_OLD_CLASSES: ["aeroplane", "bicycle", "bird", "boat", "bottle",
                       "bus", "car", "cat", "chair", "cow"]
    NAME_NEW_CLASSES: ["diningtable", "dog", "horse", "motorbike", "person",
                       "pottedplant", "sheep", "sofa", "train", "tvmonitor"]
    NAME_EXCLUDED_CLASSES: []
DATASETS:
  TRAIN: ("voc_2007_train", "voc_2007_val")
  TEST: ("voc_2007_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 0
SOLVER:
  BASE_LR: 0.0001 # start learning rate
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1  # learning rate decay
  STEPS: (30000,)
  MAX_ITER: 40000 # number of iteration
  CHECKPOINT_PERIOD: 2500 # number of iteration to generate check point
  IMS_PER_BATCH: 1 # number of images per batch
  MOMENTUM: 0.9
TEST: # testing strategy
  IMS_PER_BATCH: 1 # number of images per batch
OUTPUT_DIR: "/home/incremental_learning_ResNet50_C4/10_10" # path to store the result
TENSORBOARD_DIR: "/home/incremental_learning_ResNet50_C4/10_10/tensorboard"
