MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-C4"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
  RPN:
    USE_FPN: False
    ANCHOR_STRIDE: (16,)
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
    EXTERNAL_PROPOSAL: False
  ROI_HEADS:
    USE_FPN: False
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.0625,)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    NUM_CLASSES: 16 # total classes : 15 + 1
    NAME_OLD_CLASSES: []
    NAME_NEW_CLASSES: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog",
                       "horse", "motorbike", "person"]
    NAME_EXCLUDED_CLASSES: ["pottedplant", "sheep", "sofa", "train", "tvmonitor"]
DATASETS:
  TRAIN: ("voc_2007_train", "voc_2007_val")
  TEST: ("voc_2007_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001 # start learning rate
  WEIGHT_DECAY: 0.0001
  GAMMA: 0.1  # learning rate decay
  STEPS: (30000,)
  MAX_ITER: 40000 # number of iteration
  CHECKPOINT_PERIOD: 2500 # number of iteration to generate check point
  IMS_PER_BATCH: 1 # number of images per batch
  MOMENTUM: 0.9
TEST: # testing strategy
  IMS_PER_BATCH: 1 # number of images per batch
OUTPUT_DIR: "/home/incremental_learning_ResNet50_C4/RPN_15_classes_40k_steps" # path to store the result
TENSORBOARD_DIR: "/home/incremental_learning_ResNet50_C4/RPN_15_classes_40k_steps/tensorboard" # path to store tensorboard info
